# Generated by Django 4.2.10 on 2024-02-19 06:28

from django.db import migrations, models
import holmes_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('holmes_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', holmes_auth.models.HolmesUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
