# Generated by Django 4.2.10 on 2024-02-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
