# Generated by Django 4.2.10 on 2024-02-29 08:33

from django.db import migrations
from django.utils.text import slugify
from orders.models import Order
from django.db import transaction



def generate_unique_slug(order):
    # Generate a unique slug based on the order's data
    return slugify(f'id-{order.id}-by-{order.user.email}-status-{order.status}-total-{order.total}')

@transaction.atomic
def populate_order_slugs(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.slug = generate_unique_slug(order)
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_slug'),
    ]

    operations = [
        migrations.RunPython(populate_order_slugs),
    ]
