name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install
    
    - name: Run Django tests
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run python manage.py test
